### PR TITLE
Update circle line custom powerline glyph.

### LINKED ISSUE #4071: The circle line custom powerline glyph is the wrong shape
Current:

image

Expected:

image

image
image

image

### PR DESCRIPTION
**Pull request by tisilent**
fix #4071

### CODE REVIEW

**Comment by Tyriar** [comment]
State in PR:

Screenshot 2023-08-25 at 6 46 51 AM
Screenshot 2023-08-25 at 6 47 36 AM

@tisilent do you know what's happening with the middle where it seems to go inwards a little?

image

**Comment by tisilent** [comment]
I need to shift the top and bottom slightly outward. I'm adjusting it. I've been looking at this picture for a long time and my glasses are a bit blurry. 👀

**Comment by tisilent** [comment]
Hi @Tyriar, What tool are you using to zoom in on pixels.

**Comment by Tyriar** [comment]
@tisilent that's my image editor for vscode "Luna paint"

**Comment by tisilent** [comment]
@Tyriar "Luna paint" very very very nice~~~~

**Comment by Tyriar** [comment]
@tisilent ❤️ thanks, it has _a lot_ of hours in it

**Pull request merged**
