### PR TITLE
getCoordsRelativeToElement: use getBoundingClientRect and clientX/Y.

### PR DESCRIPTION
**Pull request by gou4shi1**
#1684

### CODE REVIEW

**Comment by Tyriar** [comment]
@mofux would appreciate a review on this when you get a chance, it's scary changing old code like this 😄

**Comment by mofux** [comment]
@Tyriar Please feel free to merge.

**Comment by Tyriar** [comment]
Thanks for the PR @gou4shi1, it's much better than it was 👍

**Comment by gou4shi1** [comment]
@Tyriar Thanks for your fix and merge!
@mofux Thanks for you review!

**Pull request merged**
