### PR TITLE
feat: Improve ligatures addon

### PR DESCRIPTION
**Pull request by QuiiBz**
This PR adds a new `ILigaturesOptions` to specify a custom file protocol, used to load the fonts on the computer.

The commit https://github.com/xtermjs/xterm.js/commit/e23153635d51f7fd704a9ed116617f90c289e5fe also fixes a bug in the `parse` function:
- If you use only one font with single or double-quotes, the font is only parsed but not pushed to the `families` array:
Example:
```js
parse('"FiraCode Nerd Font"')
```
returns an empty array, where
```js
parse('"FiraCode Nerd Font", monospace')
```
returns an array with both `FiraCode Nerd Font` and `monospace`.
- This issue is fixed here, we push a font if one was found but wasn't added to the array: https://github.com/xtermjs/xterm.js/blob/e23153635d51f7fd704a9ed116617f90c289e5fe/addons/xterm-addon-ligatures/src/parse.ts#L56-L59

### CODE REVIEW

**Comment by QuiiBz** [comment]
The tests error are caused by timeouts, is it normal?

**Review by Tyriar — COMMENTED** [review]
I'm not sure we want to go in this direction considering we're moving towards relying on the browser's font access API to get fonts https://github.com/xtermjs/xterm.js/pull/3264

**Comment by QuiiBz** [comment]
I’m not sure if it’s possible to enable the chrome flag (`#font-access`) in electron. If yes, does the ligatures addon will be completely removed?

**Comment by LabhanshAgrawal** [comment]
> I’m not sure if it’s possible to enable the chrome flag (`#font-access`) in electron. If yes, does the ligatures addon will be completely removed?

It can be done using `enableBlinkFeatures: 'FontAccess'` in BrowserWindow constructor options.

**Comment by QuiiBz** [comment]
> I'm not sure we want to go in this direction considering we're moving towards relying on the browser's font access API to get fonts #3264

Then should we close this PR?

**Comment by Tyriar** [comment]
Yes let's close this, thanks for the pr though.

**Comment by LabhanshAgrawal** [comment]
> The commit [e231536](https://github.com/xtermjs/xterm.js/commit/e23153635d51f7fd704a9ed116617f90c289e5fe) also fixes a bug in the `parse` function:
> 
> * If you use only one font with single or double-quotes, the font is only parsed but not pushed to the `families` array:
>   Example:
> 
> ```js
> parse('"FiraCode Nerd Font"')
> ```
> 
> returns an empty array, where
> 
> ```js
> parse('"FiraCode Nerd Font", monospace')
> ```
> 
> returns an array with both `FiraCode Nerd Font` and `monospace`.


@Tyriar @QuiiBz What about the parse bug mentioned above? Didn't look into it much, but this should be included, right?

**Comment by QuiiBz** [comment]
You are right, I forgot about this issue. The fix is pretty easy as you can see here:
https://github.com/xtermjs/xterm.js/commit/e23153635d51f7fd704a9ed116617f90c289e5fe#diff-af81cfaa712b74298aa772bcae4571c997ec176cb3ad6c1353a4e5ae3b3994b7R56-R60

**Comment by jerch** [comment]
@QuiiBz The fix will still miss the last family, if it is a quoted one. The issue results from loop, where `fontFamily` gets only pushed on the separator `,`. Suggestion:
```typescript
export default function parse(stringFamily: string): string[] {
  if (typeof stringFamily !== 'string') {
    throw new Error('Font family must be a string');
  }

  const context: IParseContext = {
    input: stringFamily,
    offset: 0
  };

  const families: string[] = [];
  let familyFromString = '';

  // Work through the input character by character until there are none left.
  // This lexing and parsing in one pass.
  while (context.offset < context.input.length) {
    const char = context.input[context.offset++];
    switch (char) {
      // String
      case '\'':
      case '"':
        if (familyFromString) {
          throw new Error('invalid declaration');
        }
        familyFromString = parseString(context, char);
        break;
      case ',':
        if (familyFromString && !families.includes(familyFromString)) {
          families.push(familyFromString);
        }
        familyFromString = '';
        break;
      default:
        // Identifiers (whitespace between families is swallowed)
        if (!/\s/.test(char)) {
          if (familyFromString) {
            throw new Error('invalid declaration');
          }
          context.offset--;
          const family = parseIdentifier(context);
          if (!families.includes(family)) {
            families.push(family);
          }
        }
    }
  }

  if (familyFromString && !families.includes(familyFromString)) {
    families.push(familyFromString);
  }

  return families;
}
```

This version also identifies declarations like `"Lucida" Grande, serif` as invalid. Furthermore it filter duplicates (not sure if thats a good idea, just cant see any use case for a later redeclaration of an already known entry).

**Comment by Tyriar** [comment]
If we can get a good failure case and add some tests for it we should fix the parsing. Ideally it would align with browser parsing https://developer.mozilla.org/en-US/docs/Web/CSS/font-family#formal_syntax

**Pull request closed without merging**
