### PR TITLE
Mac OSX: altIsMeta support

### PR DESCRIPTION
**Pull request by saamalik**
* Support for altIsMeta option
* Instead of providing third-level shift characters
* Sample demo application using new altIsMeta option

### CODE REVIEW

**Comment by saamalik** [comment]
Fixes #487

**Comment by saamalik** [comment]
@Tyriar let me know if you'd like me to make any additional changes.

**Comment by Tyriar** [comment]
@saamalik thanks for the PR 😃. What are some good keybindings for me to play around with to test this out?

**Comment by saamalik** [comment]
The common ones I use are: 

```
alt+f  move forward a word
alt+b  move backwards
alt+.  yank last argument
```

A whole list of useful functions are available here: https://www.skorks.com/2009/09/bash-shortcuts-for-maximum-productivity/

**Comment by Tyriar** [comment]
Thanks @saamalik, works great! I did a bit of clean up and this is good to go after CI passes. Thanks for looking into it 😃

**Comment by saamalik** [comment]
@Tyriar cool man! cleanup looks great too!

**Comment by timjs** [comment]
Is it possible to have a similar option for the editor itself?

An extension like [Dance](https://github.com/71/dance) to emulate Kakoune modal editing makes extensively use of meta mappings. For example, `meta+e` is equivalent to Vim's `E` "move to end of word including punctuation".

On macOS typing `option+e` enters a dead key mode to enter characters like é, á etc. and therefore is not usable as a shortcut for this motion. Using Kakoune in the terminal is no problem, because of the "Use Option-key as meta-key" in the Terminal settings.

**Comment by Tyriar** [comment]
@timjs you mean in VS Code? option+<letter> on mac is an OS-level feature that maybe you can turn off?

**Comment by timjs** [comment]
Sorry @Tyriar, I just overlooked and thought this is an issue on the VSCode repo, but it isn't. Think I'll have to find or create an issue in the right repo 😝 

Sadly you can't turn it of OS wide, only by hand crafting new keyboard layouts. Only [the macOS Terminal app has a setting to do this](http://osxdaily.com/2013/02/01/use-option-as-meta-key-in-mac-os-x-terminal/).

**Comment by Tyriar** [comment]
@timjs doesn't using alt in keybindings override it though?

**Comment by timjs** [comment]
I’m afraid not. In VSCode you're simply not able to bind anything to option+e/u/i/n because it produces a dead character. I.e. to type é in any text field on macOS, you first hit option+e which gives you the ´, and then e. The OS merges the two into é.

**Comment by Tyriar** [comment]
This keybinding correctly focused the terminal when the editor is focused for me? It ends up sending adding a ` char to the terminal which I think is already captured in some vscode issue.

```
{"key": "alt+e", "command": "workbench.action.terminal.toggleTerminal" }
```

**Comment by timjs** [comment]
It indeed works...

In the [Dance extension](https://github.com/71/dance) @71 is working on, then `when` clause contains `editorTextFocus`. Removing it does the trick! 

Thanks for sharing your ideas @Tyriar! Helped to find a solution!

**Pull request merged**
