### PR TITLE
Update global object fix

### PR DESCRIPTION
**Pull request by octoclonius**
The changes are to the `webpack.config.js` files in each of the addon's folders. I set the global object to `globalThis`. I think this should fix the addons because when I import them, I get an error saying `self` is not defined.

### CODE REVIEW

**Comment by octoclonius** [comment]
The changes are to the `webpack.config.js` to set the global object to `globalThis`. I think this should fix it.

**Review by ManojkumarV — APPROVED** [review]

**Review by ManojkumarV — CHANGES_REQUESTED** [review]
>

**Comment by GoodbyeNJN** [comment]
Is there any progress on this PR? I am also troubled by this problem, recompiling addon after using this patch works fine for me.

**Comment by FRSgit** [comment]
@Tyriar Do you think this PR is something that could be merged in nearest future? It's blocking usage of the library with nuxt (in SSR context it tends to fail).

**Review by Tyriar — APPROVED** [review]

**Pull request merged**
