### PR TITLE
Fixes Alt + click behaviour when rows are wrapped

### LINKED ISSUE #2658: Take isWrapped cell status into account when alt+clicking to navigate the prompt in the normal buffer
VS Code: https://github.com/microsoft/vscode/issues/86482

### PR DESCRIPTION
**Pull request by kumaran-14**
Fixes #2658.

### CODE REVIEW

**Comment by kumaran-14** [comment]
@Tyriar How to lint files in place? ```npm run lint``` only gives out err, but not fixes it.

**Comment by kumaran-14** [comment]
@Tyriar Some MoveToCell tests are failing. Should they be updated or, my implementation is wrong?

**Comment by Tyriar** [comment]
@kumaran-14 well this test was enforcing the old behavior which you've now broken:

```
 MoveToCell
       normal buffer
         should ignore the Y value
```

You'll need to update the test to respect the new behavior. Make sure there's a test for moving across a single line and multiple lines as well.

**Comment by kumaran-14** [comment]
@Tyriar This looks fine?

**Comment by kumaran-14** [comment]
@Tyriar This is fine?

**Comment by kumaran-14** [comment]
@Tyriar can you look into this?

**Comment by Tyriar** [comment]
@kumaran-14 I'll probably free up next week to power through xterm.js stuff and release 4.4

**Comment by kumaran-14** [comment]
@Tyriar Sure. That sounds awesome. I'd like to finish this and contribute more.

**Comment by Tyriar** [comment]
Another thing I noticed is that the current algorithm doesn't look at whether the row is wrapped, it should only move along the current wrapped row. I'm looking into fixing these issues now so we can get this merged in.

**Comment by kumaran-14** [comment]
@Tyriar How do I get the positions of buffer end?

localhost_3000_

**Comment by kumaran-14** [comment]
CI fails on windows and mac, passes on Linux.
What system did you test on?
I get this behaviour on Linux
ezgif com-video-to-gif

**Comment by kumaran-14** [comment]
@Tyriar Sure. Glad to help.

**Pull request merged**
