### PR TITLE
Add support for italic rendering

### PR DESCRIPTION
**Pull request by flybayer**
This adds support for italic rendering. 

You can test it with this command:
```bash
echo -e '\x1B[3m italic \x1B[m off'
```

Let me know if you'd like any changes or anything else!

Related to #580

### CODE REVIEW

**Comment by Tyriar** [comment]
I think the problem is the ordering when using `normal` as the weight before setting `.font` to this:

`normal italic 22.5px courier-new, courier, monospace`

Results in the fallback:

`10px sans-serif`

I'll look into fixing this.

**Comment by Tyriar** [comment]
Should be fixed now, just needed to rearrange the font attributes.

**Comment by Tyriar** [comment]
@bgw FYI I'll merge this in, conflicts should be minimal in your PR

**Comment by ceoshikhar** [comment]
image
Still the italics aren't rendering for me. Any solution?

**Comment by Tyriar** [comment]
Works for me:

image

Guessing it's your font config.

**Comment by shivapoudel** [comment]
@Tyriar Help is appreciated for this Cascadia Code ticket https://github.com/microsoft/cascadia-code/issues/515

**Pull request merged**
