### PR TITLE
Add Hyper to list of apps

### PR DESCRIPTION
**Pull request by jonaustin**
https://github.com/zeit/hyper/blob/82c7afbeecf5a0c455075868cd23585fce95cf68/package.json#L197

### CODE REVIEW

**Comment by Tyriar** [comment]
It might be best to wait until Hyper v2 ships before adding it? /cc @chabou

**Comment by chabou** [comment]
yes please!
Matter of days.

@jonaustin thank you for this PR 🙏

**Comment by jonaustin** [comment]
@chabou Thanks for xterm.js!

**Comment by Tyriar** [comment]
Boom https://zeit.co/blog/hyper2 :smiley:

**Pull request merged**
