### PR TITLE
npm/npm#10074 - change prepublish to prepublishOnly

### PR DESCRIPTION
**Pull request by pro-src**
https://docs.npmjs.com/misc/scripts#prepublish-and-prepare

### CODE REVIEW

**Comment by Tyriar** [comment]
@pro-src so `prepare` runs on both `install` and `publish` and `prepublishOnly` runs only on `publish`? I think `prepublishOnly` might be even better then as currently `npm install && npm run watch` will build twice which wastes 5-10 seconds or so.

**Comment by pro-src** [comment]
I think `prepublishOnly` is a good option for now that should remove the deprecation notice but only temporarily as the plan ultimately is to replace `prepublishOnly` with `prepublish` for npm@6? Leaving only the more inituitive `prepare`(npm install/upload) and `publish`(upload only) behaviors when the dust finally settles.

**Comment by pro-src** [comment]
Feel free to close this if you don't mind the deprecation notice as it will fix itself eventually.

**Comment by Tyriar** [comment]
Oh I see, well it looks like the eventual `prepublish` behavior is what we're after.

**Pull request closed without merging**
