### PR TITLE
Fix #2714 - Start demo server before running integration tests

### LINKED ISSUE #2714: Have integration tests run their own server on a port other than 3000
Right now the tests rely on the demo being up and running on port 3000, it would be nicer if instead the tests set up their own server on a different port and tore it down after running the tests.

### PR DESCRIPTION
**Pull request by bmf-ribeiro**
Fixes #2714 
- Start demo server before running integration tests
- Use port 3001 instead of  3000 to not conflict with the demo

### CODE REVIEW

**Review by Tyriar — CHANGES_REQUESTED** [review]
This is great!

We can also remove the hacky server starts in the linux and mac integration tests jobs, reducing CI time by ~10 seconds:

https://github.com/xtermjs/xterm.js/blob/26cda84eabaa3b61f49d0a56f7aad72ebfc7aada/azure-pipelines.yml#L103-L106

**Comment by nikonso** [comment]
Okay, that makes sense, should the integration tests start running on windows as well, then?

**Comment by Tyriar** [comment]
It would be good to run windows too, I forgot why they were disabled though. Can try enable in a separate pr and see what happens?

**Comment by nikonso** [comment]
This is ready to review.

Also I opened #3299 the tests ssem to be running okay on windows.

**Review by Tyriar — APPROVED** [review]
🎉

**Pull request merged**
