### PR TITLE
Fix coveralls integration

### PR DESCRIPTION
**Pull request by Tyriar**

### CODE REVIEW

**Comment by Tyriar** [comment]
This is ready for review, looks like it's working. Check the bottom of https://coveralls.io/github/xtermjs/xterm.js

**Comment by jerch** [comment]
@Tyriar Any idea why some of the commit messages show weird escaped html strings?

**Comment by Tyriar** [comment]
@jerch hm, I didn't see that when I was testing it, I suspect it's a bug on the website.

**Comment by Tyriar** [comment]
The next one worked:

screen shot 2018-09-21 at 8 16 20 am

**Pull request merged**
