### PR TITLE
DOM renderer selection isn't re-drawn after resizing the terminal

### PR DESCRIPTION
**Pull request by rishab-pdx**
#2818 
Made behavior of terminal for selection elements consistent across all ```rendererTypes```  wrt ```onResize``` event.

### CODE REVIEW

**Comment by Tyriar** [comment]
Looking at this behavior I'm thinking maybe we should try keep the selection by clamping the start/end indexes to be within the viewport and then redrawing the screen.

It would be cool is the terminal worked just like the editor:

recording (3)

There's nothing wrong with that terminal selection, it just needs to be redrawn to cover the right portion of the terminal. For the clamp example imagine this:

image

Resized down should look like this:

image

Or maybe with the last cell of the last row selected 🤔, we probably want to keep the `\n` at the very least.

**Comment by rishab-pdx** [comment]
Makes sense with keeping up the last ```\n``` if last cell of the last row is selected.

**Comment by tabaddor** [comment]
> There's nothing wrong with that terminal selection, it just needs to be redrawn to cover the right portion of the terminal. 

All renderer types need to be re-drawn to cover the right portion when resized, or just the DOM type, or just keep the new line character for the DOM type?

**Comment by Tyriar** [comment]
Closing for now as it's a bit stale, additional changes welcome though.

**Pull request closed without merging**
