### PR TITLE
Include base/ platform from VS Code, adopt DomScrollableElement and introduce esbuild

### PR DESCRIPTION
**Pull request by Tyriar**
Succeeds https://github.com/xtermjs/xterm.js/pull/5076

### CODE REVIEW

**Comment by Tyriar** [comment]
I stopped this briefly to work on some debt and to bring some of the changes here into `main` in smaller PRs. Here is the current `main` output usage:

| Use | Path | Format | Runtime | Note
|---|---|---|---|---
| Demo (/ and /test) | demo/dist/client-bundle.js | bundle | browser | Used in API/playwright tests
| Unit tests | out/ | tsc | node.js | Running in a real browser would be nice
| ~~API tests~~ | ~~out-test/api/~~ | tsc | node.js | Removed in [#5080](https://github.com/xtermjs/xterm.js/pull/5080)
| Integration tests | out-test/playwright/ | tsc | node.js
| Benchmark | out-test/benchmark/ | tsc | node.js
| @xterm/xterm package | lib/xterm.js | bundle | browser
| @xterm/headless package | headless/lib-headless/xterm-headless.js | bundle | node.js

**Comment by Tyriar** [comment]
And the current output usage on this branch (I think):

| Use | Path | Format | Runtime | Note
|---|---|---|---|---
| Demo (/ and /test) | demo/dist/client-bundle.js | bundle | browser | Used in API/playwright tests
| &nbsp; | out-tsc/ | tsc | - | Used for image addon only
| &nbsp; | out-esbuild/ | esbuild | - | Used for ligatures addon only
| &nbsp; | lib/ | esbuild | - | Used for other addons (this might require packaging atm?)
| Unit tests | out-tsc/ | tsc | node.js | Running in a real browser would be nice
| API tests | out-tsc/test-api/ | tsc | node.js
| Integration tests | out-tsc/test-playwright/ | tsc | node.js
| Benchmark | out-tsc/test-benchmark/ | tsc | node.js
| @xterm/xterm package | lib/xterm.js | bundle | browser
| @xterm/headless package | headless/lib-headless/xterm-headless.js | bundle | node.js

**Comment by Tyriar** [comment]
`main`:

image

Proposal (probably needs a different PR):

image

**Comment by jerch** [comment]
@Tyriar Plz just ping me, if you think this is ready to have a look from my side. Seems there are still some merge conflicts from your ESM transition, and I dont want to interfere in the middle of that transition to not over-complicate things.

**Comment by Tyriar** [comment]
@jerch yep planning on closing and redoing this PR today, the next one will be significantly smaller (ignoring `base/`) since esbuild was added in the other PR

**Comment by Tyriar** [comment]
Closing in favor of https://github.com/xtermjs/xterm.js/pull/5096

**Pull request closed without merging**
