### PR TITLE
Report device status directly via emit

### LINKED ISSUE #1579: node-pty terminals jump to bottom when a .NET Core console app requests for a cursor position
_From @tylerl0706 on July 21, 2018 3:13_

## Environment
- Environment: VSCode and Hyper
- OS version: macOS & Fedora 28

### Details

node-pty terminals jump to the bottom when a .NET Core console app requests for a cursor position. In other terminals (iterm, terminal.app), it does not.

This only happens on unix/linux OS's - Windows works as expected.

This is easily reproducible in PowerShell since it's built on .NET Core.

### Steps to reproduce

1. have [PowerShell on unix](https://github.com/powershell/powershell#get-powershell)
2. hit enter a bunch (until the page starts scrolling)
3. run this
```powershell
while ($true) { $null = [Console]::CursorTop; Start-Sleep 1 }
```
4. scroll up

> Note the use of `[Console]::CursorTop` which is the cursor query. In .NET Core, this emits the report cursor position ansi escape sequence on unix-like platforms

### Actual behavior

The console window jumps down to the prompt

### Expected behavior

The console window does not move

_Copied from original issue: Microsoft/node-pty#211_

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #1579

### CODE REVIEW

**Comment by Tyriar** [comment]
> Doesn't this break order of execution and is potentially dangerous?

@mofux I considered that but convinced myself it wasn't a problem because the queue will always be small and get flushed very quickly, but you're right. I think the right fix is probably to call send with a flag (or have a different call), so the order is guaranteed. Also *all* calls to `send` inside `InputHandler` should probably be treated this way (ie. only keyboard/mouse should scroll down, not the xterm.js reporting things to the process).

**Comment by Tyriar** [comment]
I'm not even sure why the send/handler queue exists in the first place, it's been around since the fork https://github.com/chjj/term.js/blame/master/src/term.js

**Comment by mofux** [comment]
I've just been wondering the same. Looks like it's a throttling mechanism that queues data within 1ms and then sends it out (the code is somewhat irritating):
https://github.com/xtermjs/xterm.js/blob/6691f809069a549b4808cd2e055398d2da15db37/src/Terminal.ts#L1583-L1592

We might try to get rid of send() and call handler directly. If I'm reading it correctly, you are trying to skip this section of code in the handler, no?

https://github.com/xtermjs/xterm.js/blob/6691f809069a549b4808cd2e055398d2da15db37/src/Terminal.ts#L1814-L1817

**Comment by mofux** [comment]
Thinking about it a little longer, the queue stuff could be done by the consumer of the 'data' event if it was really desired (e.g. throttling data emitted over a WebSocket).

**Comment by Tyriar** [comment]
@mofux but that would be buffering for a different set of data, that's everything going into the terminal, send/handler is *some of* the stuff going to the process from either the user or requested by the process. Keyboard events and composition events go directly to `handler`.

**Comment by mofux** [comment]
Mmmh I mean, if the consumer does:
```javascript
terminal.on('data', (data) => {
   pty.write(data);
});
```
The `data` he gets there is coming from both, `Terminal.handler` and `Terminal.send` (which is calling `Terminal.handler`), because `Terminal.send` does a `this.emit("data", data)`

**Comment by Tyriar** [comment]
@mofux ah yeah, I guess you might want to do that if the process is not local, but in general very little data comes from that event.

**Comment by Tyriar** [comment]
@mofux I removed Terminal.send in the last commit

**Comment by mofux** [comment]
LGTM, hope there is nothing official using `Terminal.send` anymore - had a quick look but didn't find any references, so I guess its fine 😅

**Comment by Tyriar** [comment]
@mofux yeah I think I covered everything inside xterm.js. VS Code actually uses `send` so I need to fix that up :stuck_out_tongue:

**Pull request merged**
