### PR TITLE
Start of improved layering

### PR DESCRIPTION
**Pull request by Tyriar**
Curious what people think of this change, I haven't gone and done a polish pass on this yet but the basic structure I think we should start with when considering #1507 is there.

- Created `IKeyboardEvent` in `common`
- Moved key event to escape sequence translation into `core/input/Keyboard.ts` and added some tests
- Introduced `public` which is the new API. This will allow us to make changes to `./src/Terminal` and eventually move it into `core`. This will break any integrations that access private API (which we don't guarantee).

### CODE REVIEW

**Comment by mofux** [comment]
Can we safely merge this without breaking compatibility of the 3.x releases, or should this be targeted towards a 4.0 release? I'm a bit afraid the changes in this PR become stale if this hangs around for too long. I think as long as we maintain compatibility with the public 3.x api it should be okay to merge, no?

**Comment by Tyriar** [comment]
I think this maintains the public API fine. It will break VS Code for example but that's because [`buffer` is touched](https://github.com/Microsoft/vscode/blob/bd5ee49f8899676bce2eabcae7dd781299973eef/src/typings/vscode-xterm.d.ts#L674).

I'll polish it up now as merging this will really help with pulling components into their correct spots.

**Comment by Tyriar** [comment]
Ok I think it's ready for proper review(s)

**Comment by mofux** [comment]
Still a long way to go, but it's a good start 😅Tested locally and works fine 👍

**Comment by Tyriar** [comment]
Works in VS Code so merging in

**Pull request merged**
