### PR TITLE
move image addon to base repo

### PR DESCRIPTION
**Pull request by jerch**
Moves the image addon code over to the base repo.

TODO:
- [x] move code
- [x] adjust CI scripts to run inwasm task automatically
- [x] integrate with demo
  - [x] pass API tests
  - [x] add ctor & image link options to demo
- [x] pass all unit tests
- [x] pass linter

### CODE REVIEW

**Comment by jerch** [comment]
@Tyriar Read for review. The code is the same as the last patch release (0.4.2), except the license entries (all adjusted).

**Comment by jerch** [comment]
@Tyriar Not sure whats going on with azure atm, both macos and windows runner give me different timeout issues. Tried to mitigate them somewhat, not sure if they are all gone now...

**Comment by jerch** [comment]
@Tyriar Those timeout issues with heavy load CI runners are really nasty. Its a bit tricky to wait for the state change in the remote browser engine. Tried to replace several waits with `pollFor`, sadly idk how to express "ensure that value xy does not change" with it. We kinda lack an event from the render logic telling us, that all pending write buffer data was finally applied to the output states. How do you work around that issue in the canvas and webgl renderer?

**Comment by jerch** [comment]
Jesus, the failing tests are really annoying, all version I tested above pass locally just fine, grrr. :exploding_head:

**Comment by Tyriar** [comment]
@jerch good to merge when you're ready as this is all pretty separated from the core code. We have a few more changes from the old repo to include as well is all.

**Comment by jerch** [comment]
@Tyriar I will go though your comments in https://github.com/jerch/xterm-addon-image/issues/55 and transfer the missing changes here as well before merging.

**Pull request merged**
