### PR TITLE
fix: change textarea to input

### PR DESCRIPTION
**Pull request by testrocket**
It changes HTMLTextAreaElement to HTMLInputElement element with type="password" to disable suggestions on android mobile devices.

### CODE REVIEW

**Review by jerch — CHANGES_REQUESTED** [review]
Sorry this gets a downvote from my side at the current stage:

Changing a DOM element type, even internally, is a big deal, it might trigger faulty behavior on other ends.

_How to proceed from here?_
Care to give a bit more context? There no issue linked to it, what would be helpful to repro and comprehend the problem, and discuss possible solutions. Here it is unclear what you have tried already.

Note that the textarea thingy is a hack to get around certain limitations of key input events, those all have to work as before - from event propagation and input reading (composed keys?) up to the repositioning trick for IME popups. Several of those things are not covered by our tests, thus need manual testing.

**Review by Tyriar — CHANGES_REQUESTED** [review]
Yeah I'm pretty sure this will cause a bunch of weird regressions, additionally we don't want it to be marked as a password field because that would cause problems in the screen reader support.

**Comment by testrocket** [comment]
I appologize for this PR. This was a mistake - I wanted create a PR for a fork and for some reason it landed here. Again sorry for that.

**Comment by Tyriar** [comment]
No worries 🙂

**Pull request closed without merging**
