### PR TITLE
Enable using ligatures addon outside electron

### PR DESCRIPTION
**Pull request by LabhanshAgrawal**
Based on the discussion from #958 
To test this in the demo make sure to enable `#font-access` in `chrome://flags`
And then set some font with ligatures
Creating as draft right now as I still need to look a bit into the webpack stuff.

### CODE REVIEW

**Comment by Tyriar** [comment]
This didn't seem to work for me with Fira Code and any of the 3 renderers (I think only dom and maybe canvas works with ligatures atm?). Any hints to get it to work? I enabled the chrome flag.

**Comment by LabhanshAgrawal** [comment]
After checking this out you'd have to do a `yarn` install at the root as there's an update to the dependencies. (In case you haven't done this already)

Also, I guess I need to look into the tests.

**Comment by LabhanshAgrawal** [comment]
Also, you'd need to relaunch chrome after changing the flag. (I don't remember if it asks for relaunch itself)
Are getting any error on the console?

**Comment by LabhanshAgrawal** [comment]
@Tyriar did it work for you?

**Comment by Tyriar** [comment]
There was an error in console:

> SecurityError User activation is required.

No prompt though.

I tried disabling ligatures by default so I can check the box and then I get this:

Screen Shot 2021-04-02 at 6 49 33 AM

Clicking allow didn't work though, even after reloading and trying again.

**Comment by Tyriar** [comment]
Screen Shot 2021-04-02 at 6 50 57 AM

**Comment by Tyriar** [comment]
Oh actually, it does work after that and setting the font. The prompt is a bit of a pain though that it needs user action 🤔

**Comment by Tyriar** [comment]
😍 

Screen Shot 2021-04-02 at 6 53 27 AM

**Review by Tyriar — CHANGES_REQUESTED** [review]

**Comment by LabhanshAgrawal** [comment]
Will add the comments as you mentioned.
Expect a bit slow progress on the tests and webpack stuff though, as I'm caught up in a lot of work recently.
Great to see that I didn't have to use `It works on my machine though` 😜

**Comment by LabhanshAgrawal** [comment]
The prompt doesn't come after the first time AFAIK so that should be ok.

**Comment by Tyriar** [comment]
> The prompt doesn't come after the first time AFAIK so that should be ok.

Yep, we'd want to keep it off by default and call this out in the readme though that it may cause a permissions prompt and will require to be hooked up to a "user event".

**Comment by Tyriar** [comment]
The tests hang because loading the font fails

Screen Shot 2021-04-02 at 8 08 19 AM

**Review by Tyriar — APPROVED** [review]
Thanks for the hard word 🙂

**Comment by LabhanshAgrawal** [comment]
Thanks for resolving the tests and merging it 😊.
I hope this will help speed up development on the ligatures addon.
Cheers

**Pull request merged**
