### PR TITLE
Added Terminal.getRangeAsHTML()

### LINKED ISSUE #1883: Copying HTML-formatted output
Please consider adding an API to copy terminal contents as a HTML string.

### PR DESCRIPTION
**Pull request by Eugeny**
fixes #1883

### CODE REVIEW

**Comment by Eugeny** [comment]
I suppose you could expose methods to obtain cell attributes in `BufferLineApiView`?

**Comment by jerch** [comment]
How about this:
```TS
interface ... {
  // flags
  bold: boolean;
  underline: boolean;
  ...
  // colors
  fgColorMode: ColorModeEnum;  // enum reflecting CM_P16, CM_P256 and CM_RGB
  fgColor: number; // actual color number (-1 means default color)
  fgColorHex: string; // property for hex repr (empty string means default color)
}
```

**Comment by Tyriar** [comment]
We could use union types for the color?

```
interface IBufferCell {
  readonly color: BufferCellColorAnsi16 | BufferCellColorAnsi256 | BufferCellColor24Bit;
}
```

**Comment by jerch** [comment]
@Tyriar Sure, just wondering how each type would look like?

**Comment by Tyriar** [comment]
Something like this?

```ts
interface IBufferCell {
  readonly color: IBufferCellColorAnsi16 | IBufferCellColorAnsi256 | IColor;
}

interface IBufferCellColorAnsi16 {
	ansi16Code: number;
	actualColor: IColor;
}

interface IBufferCellColorAnsi256 {
	ansi256Code: number;
	actualColor: IColor;
}

interface IColor {
	red: number;
	green: number;
	blue: number;
	hex: string;
}
```

**Comment by Tyriar** [comment]
Alternatively:

```ts
interface IBufferCell {
	readonly colorMode: ColorMode;
	readonly colorCode: number;
	readonly color: IColor;
}

enum ColorMode {
	Ansi16,
	Ansi256,
	TrueColor
}

interface IColor {
	red: number;
	green: number;
	blue: number;
	hex: string;
}
```

**Comment by jerch** [comment]
@Tyriar Hmm maybe the second one is easier to work with? For the first one I see troubles to distingish the color modes - this would only work by `instanceof` check or by explicit member checks against `ansi16Code` etc?

**Comment by Tyriar** [comment]
Yeah I'm leaning towards the second one too, moved this to https://github.com/xtermjs/xterm.js/issues/2225 and https://github.com/xtermjs/xterm.js/issues/2226

Let's close this off for now as the solution would look pretty different to this PR. @Eugeny would love your help on those APIs if you have bandwidth 😃

**Pull request closed without merging**
