### PR TITLE
Implemented smooth scrolling.

### PR DESCRIPTION
**Pull request by PoetaKodu**
Hello everyone.

I implemented smooth scrolling. I was annoyed that every time I scroll terminal in VS Code I lose track (see #1140 and https://github.com/microsoft/vscode/issues/125950).
The option is disabled by default but can be enabled using terminal options.

Preview:
https://youtu.be/BCYdZwydmLw

### CODE REVIEW

**Review by Tyriar — COMMENTED** [review]
@PoetaKodu very cool 👍 will try get a review done this week/early next week. The main thing I want to check out is how the settings work, trackpad vs wheel and how close the experience is to monaco.

**Comment by Eugeny** [comment]
Tested and trackpad scrolling isn't affected by the new option :+1:

**Review by Tyriar — COMMENTED** [review]
Looking into this now, my first impressions are:

- The scroll speed is too slow, looks like monaco has a smooth scroll duration of 125ms and it feels a lot more responsive because of that
- `smoothScrollingStepInterval` seems like we don't need it and it should instead be replaced by `requestAnimationFrame`
- A duration would be preferable to `smoothScrollingSpeed`, so the pointer device tells the terminal how much to scroll and smooth scroll animates that over x milliseconds. If the animation happens based on a number of lines each frame then scrolling a large amount of lines seems like it would be a bad experience?

**Review by Tyriar — CHANGES_REQUESTED** [review]
Yeah the above is my main feedback, it would be better to move to duration-based scrolling and we should use `requestAnimationFrame` instead of `setTimeout`/`setInterval`. Interested in your thoughts, thanks!

**Comment by Tyriar** [comment]
Implemented the needed changes in https://github.com/xtermjs/xterm.js/pull/3940

**Pull request closed without merging**
