### PR TITLE
Fix NPE in _setTheme

### LINKED ISSUE #2220: Cannot read property 'setTheme' of undefined
Hi, we've had such code:
```
this.terminal.setOption('theme', ....);
this.terminal.open(....);
```

However, with the latest changes, the internal `_colorManager` gets initialized on `.open()`, thus the first line fails with:
```
TypeError: Cannot read property 'setTheme' of undefined
    at e._setTheme (Terminal.js.pre-build-optimizer.js:587)
    at e.setOption (Terminal.js.pre-build-optimizer.js:307)
    at t.setOption (Terminal.js.pre-build-optimizer.js:193)
```

It's an easy fix on our side (just swap two lines), however, it makes sense to decouple visual customization from connectivity responsibilities. Was it an unintentional change?

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #2220

### CODE REVIEW

**Comment by Tyriar** [comment]
@jerch are you sure about that? `Terminal.open` should call `_setTheme` with `options.theme` which is still valid I think?

**Comment by Tyriar** [comment]
Also this is one of the class of bugs that won't happen anymore when we move this part of strict mode

**Comment by jerch** [comment]
@Well the OP calls `setTheme` before `open`, thus this fix will silently ignore the `setTheme` call.

**Comment by Tyriar** [comment]
Nah I just verified that it works, `setOption('theme'` sets `this.optionsService.options.theme`, this is used in `open` to recall `_setTheme`.

**Comment by Tyriar** [comment]
And yes this will get much more polished and less error prone when the theme stuff is all hooked up with the new architecture.

**Comment by JounQin** [comment]
https://unpkg.com/xterm@3.14.4/lib/Terminal.js
image
v3.14.4 on npm is still broken...

**Comment by Tyriar** [comment]
@JounQin reopened https://github.com/xtermjs/xterm.js/issues/2220 and set milestone

**Pull request merged**
