### PR TITLE
input: handle dead keys

### LINKED ISSUE #2151: Scandinavian keyboard layout can't handle input tilde (~)
To type `~` with Finnish/Swedish keyboard I have to press hotkey `alt+^`:
image

After that it shows something similar to `~` but right after when I press any other character (except Enter) it will erase "pre-tilde" symbol. Press `Enter` "converts" to normal ~ and nothing more (without real Enter).

I checked how this works with vanilla JS and it seems something wrong at browser-level:
image

Is it fixable? Wdyt?

## Related bugs:
https://github.com/xtermjs/xterm.js/issues/174

## Details
- Browser and browser version: `Chrome (latest)`
- OS version: `MacOS X (latest)`
- xterm.js version: `3.14.0`

### Steps to reproduce
1. Add  support of Finnish keyboard in your OS
2. Try to use ~ from keyboard

### PR DESCRIPTION
**Pull request by Eugeny**
Fixes #2151
This adds extra handling to avoid canceling `keydown` events dead keys, since canceling a dead key's own `keydown` will cancel the future `keydown` for the combined character.

The typical event flow for e.g. `Swedish Tilde` + `Forward Slash` is: 

* While canceling keydown (current):
image
 
* Without canceling keydown (fixed):
image

For clarity, we want to let through the next `keydown` event that is responsible for a future `keypress`/`input` (so not just the "next" one since it might be a modifier key), hence the order of the checks.

### CODE REVIEW

**Review by Tyriar — APPROVED** [review]
Change looks fine, I'll assume you're better off testing this one than me 👍

**Comment by Tyriar** [comment]
@Eugeny does this fix https://github.com/microsoft/vscode/issues/82489?

**Comment by Eugeny** [comment]
I suppose it might, but I have only tested that specific tilde combination problem so far.

**Comment by Eugeny** [comment]
Yep, that one's fixed too.

**Pull request merged**
