### PR TITLE
Add allowNonHttpProtocols option to ILinkHandler

### PR DESCRIPTION
**Pull request by Ry0taK**
This pull request adds an option called `allowNonHttpProtocols` to `ILinkHandler`.
When this option is false, all non-HTTP URLs will be ignored in OscLinkProvider.

### CODE REVIEW

**Review by Tyriar — APPROVED** [review]
Thanks 🙂

**Comment by Tyriar** [comment]
Marking as (soft) breaking change to remember to include a note in the release notes

**Comment by jerch** [comment]
Sorry to say that - but I find this addition w'o any discussion abit weird. Why is `http(s)` treated with prefiltering here? I know that hyperlinks are mostly about HTTP stuff, but thats not necessarily true anymore for some embedder with a limited use case.

If we want prefiltering on protocols, as this PR suggests, I think we should introduce a whitelist option like `allowed_protocols = ['http', ...]`, maybe defaulting to `['http', 'https']`. This way an embedder can customize the prefilter, eg. skip 'http' if their security policy demands it. Or allow only 'mailto' for whatever reason...

**Comment by Tyriar** [comment]
This was a result of an email discussion. I wanted to ensure ultimate flexibility which this allows (just say true) while at the same time being safe by default, even if the embedder ignores the doc comment on linkHandler.

**Comment by Tyriar** [comment]
The main concern is links like javascript:... can run

**Pull request merged**
