### PR TITLE
Add support for ESM via esbuild

### PR DESCRIPTION
**Pull request by Tyriar**
This PR includes the esbuild-related parts from https://github.com/xtermjs/xterm.js/pull/5077

This is roughly how the dependencies work currently:

image

The big wins here are:

- ESM support shipped in parallel via the `module` properly and `lib/xterm.mjs` (https://github.com/xtermjs/xterm.js/issues/2878), vscode does not use this yet but will soon hopefully (https://github.com/microsoft/vscode/issues/160416)
- Smaller bundle size for the new core ESM module (285KB -> 253KB)
- Much faster build times for the core lib and _unit_ tests
  - tsc still runs at the same speed to verify the types and for project references, but it no longer blocks the demo file bundling so iteration time is better.
- The demo now points at all the node modules, bringing it closer to what a user of xterm and its addons would do

### CODE REVIEW

**Comment by Tyriar** [comment]
Latest runs integration test off esbuild output 🎉

**Comment by Tyriar** [comment]
Ready to merge, this is much less risky then initially as the old tsc-based webpacked output is still shipped, just the ESM output is based on esbuild.

**Comment by jerch** [comment]
@Tyriar Wow, this looks like some heavy lifting to get ESM rolling, thx for doing the nasty works! :rocket: 

This diagram looks important to me - should we link that under the wiki build page? Also to me sense for me - does that mean, that internally all packages are still handled by UMD, but the final packages for delivery are ESM now? Or do we ship now UMD and ESM in the final packages?

**Comment by Tyriar** [comment]
@jerch yeah it was a bit rough, but a lot of this felt necessary in order to bring the nice scroll bars over.

> This diagram looks important to me - should we link that under the wiki build page?

Good idea, I'll clean up the diagram and stick it in contributing.md and/or the wiki.

> Also to make sense for me - does that mean, that internally all packages are still handled by UMD, but the final packages for delivery are ESM now? Or do we ship now UMD and ESM in the final packages?

We ship both which is possible by using the `main` and `module` properties in the package.json. Internally all packages use the esbuild sources and webpack is not touched at all until `yarn package` happens which is where the big perf wins come from as we don't need to wait for webpack to bundle after a change happens.

I wanted `tsc` to use `noEmit` such that we could remove `out/` and then remove `-esbuild` from those folders completely to simplify things, but in order to use project references (`"composite": true` and `"references": {...}`) we must emit the output. esbuild by itself doesn't verify types but instead just strips them out so we must run it.

**Pull request merged**
